services:
  db:
    image: postgres:16.3-alpine3.20
    container_name: postgres-db
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass

    volumes:
      - db-data:/var/lib/postgresql/data
#      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
volumes:
  db-data: